server:
  port: 8070
spring:
  application:
    name: crawlerConsumer
  cloud:
    nacos:
      server-addr: 121.5.69.88:8848 # nacos服务地址
      discovery:
        ip: consumer # 此服务的公网ip
  boot:
    admin:
      client:
        url: http://121.5.69.88:3795


feign:
  client:
    config:
      default:
        logger-level: basic
        connectTimeout: 200000
        readTimeout: 200000



#监控配置 开启所有监控
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
